/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminOnboardRouteImport } from './routes/admin.onboard'
import { Route as ChangeVectorIdRouteImport } from './routes/change.$vectorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnboardRoute = AdminOnboardRouteImport.update({
  id: '/admin/onboard',
  path: '/admin/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeVectorIdRoute = ChangeVectorIdRouteImport.update({
  id: '/change/$vectorId',
  path: '/change/$vectorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/explorer': typeof ExplorerRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/admin/onboard': typeof AdminOnboardRoute
  '/change/$vectorId': typeof ChangeVectorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/explorer': typeof ExplorerRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/admin/onboard': typeof AdminOnboardRoute
  '/change/$vectorId': typeof ChangeVectorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/explorer': typeof ExplorerRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/admin/onboard': typeof AdminOnboardRoute
  '/change/$vectorId': typeof ChangeVectorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clusters'
    | '/explorer'
    | '/review'
    | '/search'
    | '/admin/onboard'
    | '/change/$vectorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clusters'
    | '/explorer'
    | '/review'
    | '/search'
    | '/admin/onboard'
    | '/change/$vectorId'
  id:
    | '__root__'
    | '/'
    | '/clusters'
    | '/explorer'
    | '/review'
    | '/search'
    | '/admin/onboard'
    | '/change/$vectorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClustersRoute: typeof ClustersRoute
  ExplorerRoute: typeof ExplorerRoute
  ReviewRoute: typeof ReviewRoute
  SearchRoute: typeof SearchRoute
  AdminOnboardRoute: typeof AdminOnboardRoute
  ChangeVectorIdRoute: typeof ChangeVectorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/onboard': {
      id: '/admin/onboard'
      path: '/admin/onboard'
      fullPath: '/admin/onboard'
      preLoaderRoute: typeof AdminOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change/$vectorId': {
      id: '/change/$vectorId'
      path: '/change/$vectorId'
      fullPath: '/change/$vectorId'
      preLoaderRoute: typeof ChangeVectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClustersRoute: ClustersRoute,
  ExplorerRoute: ExplorerRoute,
  ReviewRoute: ReviewRoute,
  SearchRoute: SearchRoute,
  AdminOnboardRoute: AdminOnboardRoute,
  ChangeVectorIdRoute: ChangeVectorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

